#!/usr/local/cpanel/3rdparty/bin/perl

use strict;
use warnings;

use lib "../ea-tools/lib/ea4_tool";    # assumes ea-tools is checked out next to this repo
use ea4_tool::util ();

ea4_tool::util::write_ea4_manifest("SOURCES/pkg-manifest.json");

